# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 09:27
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField()),
                ('content', redactor.fields.RedactorField()),
                ('excerpt', redactor.fields.RedactorField(blank=True, null=True)),
                ('blog_photo', models.ImageField(blank=True, upload_to=blog.models._image_path)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField()),
                ('status', models.CharField(choices=[('pb', 'Public'), ('prv', 'Private'), ('dr', 'Draft')], default='dr', max_length=10)),
                ('tags', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
