# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171219_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
