# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 09:14
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group_coaching', '0003_auto_20171225_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingevent',
            name='logistics',
            field=redactor.fields.RedactorField(default='<ul>\n    <li><p>8 group sessions total</p></li>\n    <li><p>Weekly “office hours” (TBD in the new year) over the phone where I’m available for troubleshooting, Q&A, and check-ins</p></li>\n    <li><p>Formation of daily self-care practice-exercises (Monday through Friday) to help you stay focused, build momentum, and move forward throughout the week</p></li>\n    <li><p>Tailored invitations to work on between sessions to help you get stronger and more free</p></li>\n</ul>'),
        ),
        migrations.AlterField(
            model_name='coachingevent',
            name='outline',
            field=redactor.fields.RedactorField(default='<ul>\n      <li><p>Session 1 &amp; 2 - Liberate our minds by understanding and REMOVING the negative effects of historical and individual trauma.</p></li>\n\n      <li><p>Session 3 &amp; 4 Understand your current self-care practices and design ones that support you in developing you ideal self.</p></li>\n\n      <li><p>Session 5 &amp; 6  Clarify your values and beliefs (including the limiting ones) in order to begin living an intentional, joy filled life.</p></li>\n\n      <li><p>Session 7 &amp; 8 - Begin designing life goals in order to crate clarity, purpose and restore passion.</p></li>\n    </ul>'),
        ),
    ]
