# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 14:30
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group_coaching', '0004_auto_20171226_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingevent',
            name='logistics',
            field=redactor.fields.RedactorField(default='<ul>\n    <li><p>8 group sessions total</p></li>\n    <li><p>Total of 12 phenomenal women per group</p></li>\n    <li><p>Weekly "office hours" (TBA) over the phone where I’m available for troubleshooting, Q&A, and check-ins</p></li>\n    <li><p>Formation of daily self-care practice-exercises (Monday through Friday) to help you stay focused, build momentum, and move forward throughout the week</p></li>\n    <li><p>Tailored invitations to work on between sessions to help you get stronger and more free</p></li>\n</ul>'),
        ),
        migrations.AlterField(
            model_name='coachingevent',
            name='outline',
            field=redactor.fields.RedactorField(default='\n<div>\n    <h4>Session 1 &amp; 2  &mdash; Foundational Self Love</h4>\n    <p class="group-coach-subhead">Topics:</p>\n    <ul>\n        <li>Developing self-care practices, transforming self-talk</li>\n        <li>Identifying the origin of negative self-talk</li>\n        <li>Identifying trauma’s lies, finding personal truths</li>\n    </ul>\n</div>\n<div>\n    <h4>Session 3 &amp; 4 &mdash; Transforming Beliefs</h4>\n    <p class="group-coach-subhead">Topics:</p>\n    <ul>\n        <li>Understanding the common limiting beliefs associated with having to navigate domestic violence and childhood abuse.</li>\n        <li>Identifying your "Goliath limited beliefs" and their impact on the way you view safety, trust, power/control, intimacy, and self esteem.</li>\n        <li>Learn tools to challenge and revise old negative patterns of thinking.</li>\n    </ul>\n</div>\n<div>\n    <h4>Session 5 &amp; 6 &mdash; Elevating Core Values</h4>\n    <p class="group-coach-subhead">Topics:</p>\n    <ul>\n        <li>Articulate your values and WHY you have them</li>\n        <li>Identify and re-design your "rulebook" for success and how to acquire what you value; one\'s judgment of what is important in life.</li>\n        <li>Align beliefs to achieve practice values.</li>\n    </ul>\n</div>\n<div>\n    <h4>Session 7 &amp; 8 &mdash; Restoring Passion</h4>\n    <p class="group-coach-subhead">Topics:</p>\n    <ul>\n        <li>Identify an area of "Play" and engage in it weekly or monthly.</li>\n        <li>Articulate your life goals in the following areas: career, physical health, mental health, emotional health, and spirituality.</li>\n        <li>Create a 90-day life goal plan for different life areas.</li>\n        <li>Receive guidance and support to create clarity, purpose and restore your passion.</li>\n    </ul>\n</div>'),
        ),
    ]
