# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_coaching', '0005_auto_20180830_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachingevent',
            options={'verbose_name': 'Counseling Event', 'verbose_name_plural': 'Counseling Events'},
        ),
        migrations.AddField(
            model_name='coachingevent',
            name='final_payment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
