# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_coaching', '0006_auto_20181107_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingevent',
            name='final_payment_date',
            field=models.DateField(),
        ),
    ]
