# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True),
        ),
    ]
