# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20171214_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Mental Health Resource', 'verbose_name_plural': 'Mental Health Resources'},
        ),
    ]
