# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='subtitle',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
