# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaking', '0003_auto_20171225_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
