# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 04:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import healers.models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('event_photo', models.ImageField(blank=True, upload_to=healers.models._image_path)),
                ('date_published', models.DateTimeField(default=datetime.datetime.now)),
                ('event_date', models.DateField()),
                ('event_time', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='address', serialize=False, to='healers.Event')),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(default='Seattle', max_length=64)),
                ('state', localflavor.us.models.USStateField(default='WA')),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
    ]
