# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
