# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('meeting_days', models.CharField(max_length=1024)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('external_link', models.URLField(max_length=1024)),
                ('location', models.CharField(default='600 North 65th street, Seattle, WA', max_length=1024)),
                ('logistics', models.TextField(default='<ul>\n    <li>8 group sessions total</li>\n    <li>Weekly “office hours” (TBD in the new year) over the phone where I’m available for troubleshooting, Q&A, and check-ins</li>\n    <li>Formation of daily self-care practice-exercises (Monday through Friday) to help you stay focused, build momentum, and move forward throughout the week</li>\n    <li>Tailored invitations to work on between sessions to help you get stronger and more free</li>\n</ul>')),
                ('current_event', models.BooleanField(default=False)),
            ],
        ),
    ]
