# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_coaching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingevent',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=79.0, help_text='Cost per person ($)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='coachingevent',
            name='current_event',
            field=models.BooleanField(default=False, help_text='Is this the next group?'),
        ),
        migrations.AlterField(
            model_name='coachingevent',
            name='external_link',
            field=models.URLField(help_text='Full URL to the event invite page. Ex: https://www.eventbrite.com/...', max_length=1024),
        ),
        migrations.AlterField(
            model_name='coachingevent',
            name='meeting_days',
            field=models.CharField(default='Wednesdays', max_length=1024),
        ),
    ]
